name: qurany_cards_pro
description: "Qurany - A Quran memorization app using spaced repetition system (SRS) to help users effectively memorize the Quran through interactive features, audio recitations, and smart review scheduling."
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  flip_card: ^0.7.0
  path_provider: ^2.1.1
  flutter_html: ^3.0.0-beta.2
  shared_preferences: ^2.0.6
  shared_preferences_web: ^2.2.0
  collection: ^1.17.0
  confetti: ^0.7.0
  firebase_core: ^2.13.0
  flutter_settings_screens: ^0.3.3-null-safety
  intl: ^0.18.1
  video_player: ^2.8.1
  flutter_local_notifications: ^16.3.0
  http: ^1.1.0
  archive: ^3.3.7
  permission_handler: ^11.3.1
  cloud_firestore: ^4.8.0
  url_launcher: ^6.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/audio/
    - assets/Txt files/
    - assets/Txt files/quran-uthmani (1).txt
    - assets/Txt files/ar.muyassar.txt
    - assets/Txt files/es.garcia.txt
    - assets/Txt files/hi.farooq.txt
    - assets/Txt files/ur.maududi.txt
    - assets/Txt files/id.indonesian.txt
    - assets/Txt files/en.yusufali.txt
    - assets/Txt files/ru.kalam.txt
    - assets/Txt files/zh.jian.txt
    - assets/Txt files/tr.ozturk.txt
    - assets/images/tutorial.gif
    - assets/images/modes.gif
    - assets/images/w.png
    - assets/Txt files/quran-tajweed-numbered.txt
    - assets/Txt files/page_ayah_count.txt
  fonts:
    - family: _Othmani
      fonts:
        - asset: assets/fonts/_Othmani Regular.ttf
    - family: _UthmanTN
      fonts:
        - asset: assets/fonts/_UthmanTN_v2-0 (1).ttf
    - family: _KFGQPCAn
      fonts:
        - asset: assets/fonts/_KFGQPCAnRegular.ttf
